@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM5LCJyb2xlSWQiOjQsImlhdCI6MTc1Njk5MjIzNCwiZXhwIjoxNzU3MDc4NjM0fQ.pBmsi0-wigaA83mqwQkTaHTFtf5sqdi37ESjhuovTS8

### Admin Dashboard - Insights
GET http://localhost:3000/admin/dashboard
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

### Get all Users
GET http://localhost:3000/admin/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

### Get all Companies
GET http://localhost:3000/admin/companies
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

### Get all Jobs
GET http://localhost:3000/admin/jobs
Content-Type: application/json
Authorization: Bearer {{authToken}}
